### ISSUE TITLE
NullReferenceException when attempting to use Oracle.Managed.tt to generate my schema

### ISSUE THREAD

**Issue by jshin47** [linq2db/t4models#10]
I am new to LinqToDB and while it seems to work brilliantly for those classes I have manually defined (or generated through my own, crappy code generator) it does not seem to generate the code from the TT as it produces a NullReferenceException. The stack trace is rather long so I have pasted at the end.

The exception is generated at LinqToDB.SchemaProvider.SchemaProviderBase.ToValidName(string name) and evidently perhaps it is "name" that is null. This is occurring after calling LoadOracleMetadata(string connectionString) and I have verified that I am definitely connecting to the database as when I put in invalid credentials I get a different error. I am unable to step into the "meat" of the code generation unfortunately as there are no debug symbols for that part it seems and so I am only left observing that it seems to run for a good 30 to 60 seconds before bombing out. I have reason to think it is doing some work based on that.

I have tried toying around with the configuration options to no avail. I really want to use your code generator so please help if you can! I've produced my options (which are just the latest iteration... I tried with defaults first) and stack trace below. Thank you in advance!

```c#
<#@ template language="C#" debug="True" hostSpecific="True"                                #>
<#@ output extension=".generated.cs"                                                       #>
<#@ include file="$(ProjectDir)LinqToDB\LinqToDB.Templates\LinqToDB.Oracle.Managed.Tools.ttinclude" #>
<#@ include file="$(ProjectDir)LinqToDB\LinqToDB.Templates\PluralizationService.ttinclude"          #>
<#
	/*
		1. Copy this file to a folder where you would like to generate your data model,
		   rename it, and delete .txt extension. For example:

			MyProject
				DataModels
					MyDatabase.tt

		2. Modify the connection settings below to connect to your database.

		3. Add connection string to the web/app.config file:

			<connectionStrings>
				<add name="MyDatabase" connectionString="Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=MyServer)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=MyDatabase)));User Id=MyUser;Password=MyPassword;" providerName="Oracle" />
			</connectionStrings>

		4. To access your database use the following code:

			using (var db = new MyDatabaseDB())
			{
				var q =
					from c in db.Customers
					select c;

				foreach (var c in q)
					Console.WriteLine(c.ContactName);
			}

		5. See more at https://github.com/linq2db/t4models/blob/master/Templates/!ReadMe.LinqToDB.md.
	*/
	NamespaceName            = "DataModels";       // Namespace of the generated classes.

DataContextName          = null;               // DataContext class name. If null - database name + "DB".
BaseDataContextClass     = null;               // Base DataContext class name. If null - LinqToDB.Data.DataConnection.
GenerateConstructors     = true;               // Enforce generating DataContext constructors.
DefaultConfiguration     = null;               // Defines default configuration for default DataContext constructor.

BaseEntityClass          = null;               // Base Entity class name. If null - none.
DatabaseName             = "xxxxx";               // Table database name - [Table(Database="DatabaseName")].
GenerateDatabaseName     = false;              // Always generate table database name, even though DatabaseName is null.
IncludeDefaultSchema     = false;               // Default schema name is generated - [Table(Database="Northwind", Schema="dbo", Name="Customers")]
OneToManyAssociationType = "IEnumerable<{0}>"; // One To Many association type. Change it to "List<{0}>" if needed.
GenerateAssociations     = true;               // Enforce generating associations.
GenerateBackReferences   = true;               // Enforce generating backreference associations.

ReplaceSimilarTables     = false;               // Replaces stored procedure result class names with similar to existing table class names.
GenerateFindExtensions   = true;               // Generates find extension methods based on PKs information.
IsCompactColumns         = false;               // If true, column compact view.

PluralizeClassNames                 = false;   // If true, pluralizes table class names.
SingularizeClassNames               = true;    // If true, singularizes table class names.
PluralizeDataContextPropertyNames   = true;    // If true, pluralizes DataContext property names.
SingularizeDataContextPropertyNames = false;   // If true, singularizes DataContex pProperty names.

bool GenerateObsoleteAttributeForAliases = false;
IsCompactColumnAliases   = false;               // If true, column alias compact view.

//GetSchemaOptions.ExcludedSchemas = new[] { "TestUser", "SYSSTAT" }; // Defines excluded schemas.
GetSchemaOptions.IncludedSchemas = new[] { "xxxx" };     // Defines only included schemas.

//	LoadOracleMetadata("192.168.10.10", "1521", "DEVC", "emeddb", "emed1pass");
	LoadOracleMetadata("USER ID=xxxxxx;PASSWORD=xxxxxxxx;DATA SOURCE=192.168.x.x:1521/xxx;connection lifetime=1200");

	GenerateModel();
#>
```

```
Error	540	Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at LinqToDB.SchemaProvider.SchemaProviderBase.ToValidName(String name)
   at LinqToDB.SchemaProvider.SchemaProviderBase.<GetSchema>b__30(<>f__AnonymousType6`2 <>h__TransparentIdentifier6)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LinqToDB.SchemaProvider.SchemaProviderBase.<GetSchema>b__28(ProcedureInfo sp, IEnumerable`1 gr)
   at System.Linq.Enumerable.<GroupJoinIterator>d__6a`4.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplating897E1797A7604C7848186AA534BA116FB2E451E743FC7D66BF1E82C3B2F163C7C44083A4D9927042086139782B6614CEA30869A46C55FBEED548B8A0984CF0E5.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in c:\Unmanaged\Sources\SHORT\DevNC\FFHSPlatform\Solutions\EmedFullSuite\Emed.Net.Data\LinqToDB\LinqToDB.Templates\DataModel.ttinclude:line 53
   at Microsoft.VisualStudio.TextTemplating897E1797A7604C7848186AA534BA116FB2E451E743FC7D66BF1E82C3B2F163C7C44083A4D9927042086139782B6614CEA30869A46C55FBEED548B8A0984CF0E5.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in c:\Unmanaged\Sources\SHORT\DevNC\FFHSPlatform\Solutions\EmedFullSuite\Emed.Net.Data\LinqToDB\LinqToDB.Templates\DataModel.ttinclude:line 257
   at Microsoft.VisualStudio.TextTemplating897E1797A7604C7848186AA534BA116FB2E451E743FC7D66BF1E82C3B2F163C7C44083A4D9927042086139782B6614CEA30869A46C55FBEED548B8A0984CF0E5.GeneratedTextTransformation.LoadOracleMetadata(String connectionString) in c:\Unmanaged\Sources\SHORT\DevNC\FFHSPlatform\Solutions\EmedFullSuite\Emed.Net.Data\LinqToDB\LinqToDB.Templates\LinqToDB.Oracle.ttinclude:line 19
   at Microsoft.VisualStudio.TextTemplating897E1797A7604C7848186AA534BA116FB2E451E743FC7D66BF1E82C3B2F163C7C44083A4D9927042086139782B6614CEA30869A46C55FBEED548B8A0984CF0E5.GeneratedTextTransformation.TransformText() in c:\Unmanaged\Sources\SHORT\DevNC\FFHSPlatform\Solutions\EmedFullSuite\Emed.Net.Data\ADO\OracleDB\Linq\DataModels\CopyMe.Oracle.Managed.tt:line 67	c:\Unmanaged\Sources\SHORT\DevNC\FFHSPlatform\Solutions\EmedFullSuite\Emed.Net.Data\LinqToDB\LinqToDB.Templates\DataModel.ttinclude	53	1	Emed.Net.Data
```

**Comment by igor-tkachev** [comment]
I think I can close it.

**Comment by jshin47** [comment]
You did... thank you.

**Comment by jshin47** [comment]
I think I will try to contribute to this project when I get a better understanding of it. It is an incredibly deep project for such a small number of contributors. I'll definitely use it in some more projects
