### ISSUE TITLE
Requested value 'Hstore' was not found

### ISSUE THREAD

**Issue by borisgappov** [linq2db/t4models#35]
Database - PostgreSQL
I get an error in file DataModel.ttinclude in line 56: var db = sp.GetSchema(dataConnection, GetSchemaOptions);

My code is:
```
<#@ template debug="false" hostspecific="false" language="C#" compilerOptions="/langversion:4" #>
<#@ assembly name="C:\projects\linq2dbtest\linq2dbtest\bin\Debug\linq2db.dll" #>
<#@ assembly name="C:\projects\linq2dbtest\linq2dbtest\bin\Debug\Npgsql.dll" #>
<#@ output extension=".generated.cs"                                                   #>
<#@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude"       #>
<#@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"      #>
<#
	NamespaceName = "db";
	LoadPostgreSQLMetadata("localhost", "5432", "app", "postgres", "postgres");
	GenerateModel();
#>
```

```
Error		Running transformation: System.ArgumentException: Requested value 'Hstore' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at LinqToDB.DataProvider.DynamicDataProviderBase.GetSetParameter(Type connectionType, String parameterTypeName, String propertyName, String dbTypeName, String valueName) in c:\projects\linq2db\Source\DataProvider\DynamicDataProviderBase.cs:line 89
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider.OnConnectionTypeCreated(Type connectionType) in c:\projects\linq2db\Source\DataProvider\PostgreSQL\PostgreSQLDataProvider.cs:line 119
   at LinqToDB.DataProvider.DynamicDataProviderBase.GetConnectionType() in c:\projects\linq2db\Source\DataProvider\DynamicDataProviderBase.cs:line 40
   at LinqToDB.DataProvider.DynamicDataProviderBase.CreateConnectionInternal(String connectionString) in c:\projects\linq2db\Source\DataProvider\DynamicDataProviderBase.cs:line 63
   at LinqToDB.DataProvider.DataProviderBase.CreateConnection(String connectionString) in c:\projects\linq2db\Source\DataProvider\DataProviderBase.cs:line 76
   at LinqToDB.Data.DataConnection.get_Connection() in c:\projects\linq2db\Source\Data\DataConnection.cs:line 520
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options) in c:\projects\linq2db\Source\SchemaProvider\SchemaProviderBase.cs:line 49
   at Microsoft.VisualStudio.TextTemplating3B0EB805BB576B1802E87EFD0CAAD6DA1B5E69EC8F3276DE2F9986317C469F377BF207704046C11D083DEF2B7CCCBBFFA1FFCBB0F49E7B7127153137D921DADC.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection)
   at Microsoft.VisualStudio.TextTemplating3B0EB805BB576B1802E87EFD0CAAD6DA1B5E69EC8F3276DE2F9986317C469F377BF207704046C11D083DEF2B7CCCBBFFA1FFCBB0F49E7B7127153137D921DADC.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection)
   at Microsoft.VisualStudio.TextTemplating3B0EB805BB576B1802E87EFD0CAAD6DA1B5E69EC8F3276DE2F9986317C469F377BF207704046C11D083DEF2B7CCCBBFFA1FFCBB0F49E7B7127153137D921DADC.GeneratedTextTransformation.TransformText()	linq2dbtest	C:\projects\linq2dbtest\linq2dbtest\Models\db.tt	1
```

**Comment by ili** [comment]
Are there any keyword `Hstore` in your db? It looks like schema specific for a stored procedure...

**Comment by borisgappov** [comment]
Hi Ilya! Here is my db https://goo.gl/ZbsNFG

**Comment by ili** [comment]
Really sorry for late response. 
It looks like it is because of Npgsql version. Can you say what version are you using?

**Comment by borisgappov** [comment]
I'm sorry, I do not remember, I propose to close this ticket
