### ISSUE TITLE
LoadServerMetadata keeps crashing when trying to use CopyMe.Informix.TT

### ISSUE THREAD

**Issue by BrianLima** [linq2db/t4models#49]
For some reason it keeps adding my local machine name to uid on the connection string.

Crashes at line 58 with "Template runtime error":
`ERROR [28000] [Informix .NET provider][Informix]Incorrect password or user user@[local AD Machine] is not known on the database server.`

` em IBM.Data.Informix.DBCWrapper..ctor(IfxConnection connection)
   em IBM.Data.Informix.IfxConnectionPool.IfxConnPoolNode..ctor(IfxConnection connection)
   em IBM.Data.Informix.IfxConnectionPool.OpenNewConnection(IfxConnection connection, ConnectionPoolType ConnPoolType)
   em IBM.Data.Informix.IfxConnectionPool.Open(IfxConnection connection)
   em IBM.Data.Informix.IfxConnPoolManager.Open(IfxConnection connection)
   em IBM.Data.Informix.IfxConnection.Open()
   em LinqToDB.Data.DataConnection.get_Connection()
   em LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   em Microsoft.VisualStudio.TextTemplating87908E162B9394263A3545B1A51D6BF152D79B25EC185C7C18BF47ACB338C1529AE609801F4181BB88E6FE0A735416C16A6C9BFF1662246311AC5BD6F60AF383.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) na C:\Itaesbra\DocOP\DocOP\ClassLibrary1\LinqToDB.Templates\DataModel.ttinclude:linha 58
   em Microsoft.VisualStudio.TextTemplating87908E162B9394263A3545B1A51D6BF152D79B25EC185C7C18BF47ACB338C1529AE609801F4181BB88E6FE0A735416C16A6C9BFF1662246311AC5BD6F60AF383.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) na C:\Itaesbra\DocOP\DocOP\ClassLibrary1\LinqToDB.Templates\DataModel.ttinclude:linha 312
   em Microsoft.VisualStudio.TextTemplating87908E162B9394263A3545B1A51D6BF152D79B25EC185C7C18BF47ACB338C1529AE609801F4181BB88E6FE0A735416C16A6C9BFF1662246311AC5BD6F60AF383.GeneratedTextTransformation.LoadInformixMetadata(String host, String port, String server, String database, String uid, String password) na C:\Itaesbra\DocOP\DocOP\ClassLibrary1\LinqToDB.Templates\LinqToDB.Informix.ttinclude:linha 26
   em Microsoft.VisualStudio.TextTemplating87908E162B9394263A3545B1A51D6BF152D79B25EC185C7C18BF47ACB338C1529AE609801F4181BB88E6FE0A735416C16A6C9BFF1662246311AC5BD6F60AF383.GeneratedTextTransformation.TransformText() na C:\Itaesbra\DocOP\DocOP\ClassLibrary1\Models\CopyMe.Informix.tt:linha 46`

**Comment by ili** [comment]
Hi @BrianLima !
How does your `tt` file looks like?

**Comment by BrianLima** [comment]
`<#@ template language="C#" debug="True" hostSpecific="True"                          #>
<#@ output extension=".generated.cs"                                                 #>
<#@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.Informix.Tools.ttinclude" #>
<#@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"    #>
<#
	/*
		1. Download and install IBM Data Server Provider for .NET.

		2. Add a reference to IBM.Data.Informix.dll.

		3. Copy this file to a folder where you would like to generate your data model,
		   rename it, and delete .txt extension. For example:

			MyProject
				DataModels
					MyDatabase.tt

		4. Modify the connection settings below to connect to your database.

		5. Add connection string to the web/app.config file:

			<connectionStrings>
				<add name="MyDatabase"
					connectionString="connectionstring ommited"
					providerName="IBM.Data.Informix"/>
			</connectionStrings>

		6. To access your database use the following code:

			using (var db = new MyDatabaseDB())
			{
				var q =
					from c in db.Customers
					select c;

				foreach (var c in q)
					Console.WriteLine(c.ContactName);
			}

		7. See more at https://github.com/linq2db/t4models
	*/

	NamespaceName = "DataModels";

						//host, port, server, database, uid, password
	LoadInformixMetadata("***.***.***.***", "****", "*****", "****", "informix "*******");
	//LoadInformixMetadata("ConnectionString ommited");

	GenerateModel();
#>
`

Looks like this, i removed the connection string only.

**Comment by ili** [comment]
I do not have Informix on hand just now, i'll take a look for this issue later today!

**Comment by BrianLima** [comment]
Our instance is running inside a OpenSuse virtualized environment on a server, in case that would influence something.

**Comment by ili** [comment]
@BrianLima i'v just checked Informix T4, an had no problems. Your error says that smth is wrong with username or password. 
May be you do need to specify smth special in connection string. You can see how connection string is builded in `LinqToDB.Informix.ttinclude`

Also  you can try to use `LoadInformixMetadata(string connectionString);` method to specify 100% right connection string directly.

**Comment by BrianLima** [comment]
It crashes at the same place using individual parameters or the connection string in a whole, it always change the user on the connection string to user@localmachine even tho I didn't tell for it do this, my server is not at my local machine, it's on another server. 

I can specify that my user is Informix@myserver, it ALWAYS changes the connection string magically to Informix@myserver@[mylocalmachine].

It's not a connection string problem because I my self use the IBM.Data.Informix dll with the same connection string to connect to the same database on another app and I have no problems.

**Comment by ili** [comment]
It is really strange situation, we do not modify connection string.

**Comment by ili** [comment]
Truly saying I'm not familiar with Informix, I do use it only to run linq2db tests... In our environment we do not use `@` in user name. Looking the test configuration this one is used:
```xml
<add name="Informix"         connectionString="Host=DBHost;Service=9088;Server=ol_informix1170;Protocol=onsoctcp;Database=TestData;UID=informix;PWD=TestPassword;" providerName="IBM.Data.Informix" />
```

What if you do use just "Informix" as user name? (not Informix@myserver)

**Comment by ili** [comment]
I'v tried to play with user name in my environment:
`LoadInformixMetadata("DBHost", "9088", "ol_informix1170", "TestData", "informix@dbhost", "TestPassword")`

and i'v similar error, where my user name is shown as `informix@dbhost@DESKTOP-UD0G2KB` I think that `@DESKTOP-UD0G2KB` just used in message to show client's machine name (for logs, administrators, etc...)

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: IBM.Data.Informix.IfxException (0x80004005): ERROR [HY000] [Informix .NET provider][Informix]Unspecified System Error =  -951. sqlerrm(informix@dbhost@DESKTOP-UD0G2KB)
   at IBM.Data.Informix.DBCWrapper..ctor(IfxConnection connection)
   at IBM.Data.Informix.IfxConnectionPool.IfxConnPoolNode..ctor(IfxConnection connection)
   at IBM.Data.Informix.IfxConnectionPool.OpenNewConnection(IfxConnection connection, ConnectionPoolType ConnPoolType)
   at IBM.Data.Informix.IfxConnectionPool.Open(IfxConnection connection)
   at IBM.Data.Informix.IfxConnPoolManager.Open(IfxConnection connection)
   at IBM.Data.Informix.IfxConnection.Open()
   at LinqToDB.Data.DataConnection.get_Connection() in c:\projects\linq2db\Source\Data\DataConnection.cs:line 632
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options) in c:\projects\linq2db\Source\SchemaProvider\SchemaProviderBase.cs:line 55
   at Microsoft.VisualStudio.TextTemplating020FA0A6F78304C4DB314F5BD51360B95CE65D2F7C7CDD17E22F9EBB93F7B580D849C5AAA25FDB308D4A7C486BE5406BB9188DA4AE08ED09FBC1B06A780F787A.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in F:\job\t4models\Tests\LinqToDB\..\..\Templates\DataModel.ttinclude:line 91
   at Microsoft.VisualStudio.TextTemplating020FA0A6F78304C4DB314F5BD51360B95CE65D2F7C7CDD17E22F9EBB93F7B580D849C5AAA25FDB308D4A7C486BE5406BB9188DA4AE08ED09FBC1B06A780F787A.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in F:\job\t4models\Tests\LinqToDB\..\..\Templates\DataModel.ttinclude:line 361
   at Microsoft.VisualStudio.TextTemplating020FA0A6F78304C4DB314F5BD51360B95CE65D2F7C7CDD17E22F9EBB93F7B580D849C5AAA25FDB308D4A7C486BE5406BB9188DA4AE08ED09FBC1B06A780F787A.GeneratedTextTransformation.LoadInformixMetadata(String host, String port, String server, String database, String uid, String password) in F:\job\t4models\Tests\LinqToDB\..\..\Templates\LinqToDB.Informix.ttinclude:line 26
   at Microsoft.VisualStudio.TextTemplating020FA0A6F78304C4DB314F5BD51360B95CE65D2F7C7CDD17E22F9EBB93F7B580D849C5AAA25FDB308D4A7C486BE5406BB9188DA4AE08ED09FBC1B06A780F787A.GeneratedTextTransformation.TransformText() in F:\job\t4models\Tests\LinqToDB\Informix.tt:line 10		c:\projects\linq2db\Source\Data\DataConnection.cs	632	
```

**Comment by BrianLima** [comment]
`<add name="MyDatabase" connectionString="Host=[IP];Service=1610;Server=prd_a;Protocol=olsoctcp;Database=database;UID=informix;PWD=testpassword;" providerName="IBM.Data.Informix"/> `

Is there a way of creating logs or something? i'm not very familiar with .tt scripts.

**Comment by ili** [comment]
In general you can write simple test using linq2db sources with executing any query, make a breakpoint in https://github.com/linq2db/linq2db/blob/master/Source/Data/DataConnection.cs#L800 and look the connection string passed

**Comment by BrianLima** [comment]
Allright, I will download the sources and try this, I just might take a little longer. I'm aq bit busy with other things right now.
